name: Rust - audit

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1" # lunes 09:00

concurrency:
  group: ${{ forgejo.ref_name }}-rust-audit
  cancel-in-progress: true

jobs:
  audit:
    runs-on: rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.forgejo/actions/setup-rust
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: cargo audit
        run: cargo audit

