name: Rust - fmt

on:
  push:
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain"
      - "rust-toolchain.toml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain"
      - "rust-toolchain.toml"
  workflow_dispatch:

concurrency:
  group: ${{ forgejo.ref_name }}-rust-fmt
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.forgejo/actions/setup-rust
      - name: cargo fmt (check)
        run: cargo fmt --all -- --check

