name: Rust - deny

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
  workflow_dispatch:

concurrency:
  group: ${{ forgejo.ref_name }}-rust-deny
  cancel-in-progress: true

jobs:
  deny:
    runs-on: rust
    steps:
      - uses: actions/checkout@v4
      - uses: ./.forgejo/actions/setup-rust
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: cargo deny check
        run: cargo deny check

